### ISSUE TITLE
the strategy about setting mongodb storageclass

### ISSUE THREAD

**Issue by chenzhiwei** [IBM/ibm-mongodb-operator#15]
In document we need to ask users to set the default storageclass before installation and tell them if they don't set one we will automatically choose one:

https://docs.openshift.com/container-platform/4.1/storage/dynamic-provisioning.html#defining-storage-classes_dynamic-provisioning

The logic to choose storage class can be:

1. If the cluster has no storage class, log error message and stuck in reconcile loop
1. If there is only one default storageclass, then we don't set storageclass and let the kubernetes assign one to mongodb
1. If there are multiple default storage classes, then we choose the first one and set to sts
1. If there is no default storage class, we choose the first one and set it to mongodb sts

**Comment by gyliu513** [comment]
@chenzhiwei what is the behavior of `storageclass` selection for Kubenretes? I think we should keep same as Kubernetes.

**Comment by chenzhiwei** [comment]
Kubernetes behavior:

1. https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
2. https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass

**Comment by mikekaczmarski** [comment]
Kubernetes allow the user to specify one storageclass as the default.  This does not guarantee that the user will choose a storage class with persistentVolumeReclaimPolicy set to Retain

**Comment by mikekaczmarski** [comment]
The easiest thing to do would be to add a PREFRRED_STORAGE_CLASS rnvironment variable to the backup and restore jobs and use that storage class to update the relvant CRs in the operandConfig for mongo, monitoring, and logging if specified
