### ISSUE TITLE
bootstrap container cannot use the CA cert

### ISSUE THREAD

**Issue by kgcarr** [IBM/ibm-mongodb-operator#42]
```
bash-4.2$ ls -l
total 16
-rw-------. 1 root root    7 Feb 24 15:09 key.txt
-rw-r--r--. 1 root root  330 Feb 24 15:09 mongod.conf
-r--------. 1 root root 2021 Feb 24 15:09 tls.crt
-r--------. 1 root root 3272 Feb 24 15:09 tls.key
bash-4.2$ whoami
nobody
```

the tls.crt and tls.key come from the `mongodb-root-ca-cert` which is mounted with ownership to the root user...we don't run as root so the `install` initcontainer needs to change ownership so everything else can use it. Those were commented out in the operator's `installconfigmap`
```
# chown -R 999:999 /work-dir
    # chown -R 999:999 /data
```

Why were they commented out, can they be added back in?
@chenzhiwei

**Comment by kgcarr** [comment]
Oh, I saw this problem in a test env, but cannot recreate it in my own

**Comment by chenzhiwei** [comment]
fixed here: https://github.com/IBM/ibm-mongodb-operator/pull/37
