### ISSUE TITLE
Implement helm hooks

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-mongodb-operator#46]
There are some hook logics in the helm chart. We need to check if need to move them to the operator and move the necessary ones to the operator.
 
- Pre-install, Pre-upgrade:  https://github.ibm.com/IBMPrivateCloud/icp-mongodb/blob/master/stable/icp-mongodb/templates/mongodb-bringup-job.yaml

- Pre-delete: https://github.ibm.com/IBMPrivateCloud/icp-mongodb/blob/master/stable/icp-mongodb/templates/mongodb-takedown-job.yaml

- Post-delete: https://github.ibm.com/IBMPrivateCloud/icp-mongodb/blob/master/stable/icp-mongodb/templates/mongodb-delete-certs-job.yaml
https://github.ibm.com/IBMPrivateCloud/icp-mongodb/blob/master/stable/icp-mongodb/templates/mongodb-delete-certs-configmap.yaml

**Comment by kgcarr** [comment]
the mongodb-bringup-job is to hide the details of kubernetes secrets from helm so a user cannot see the secret with a `helm get`. Do not need

the mongodb-takedown-job reverted back to the original password to keep re-installs consistent. Do not need.

The delete certs cleaned up the client certs, which were not getting deleted by helm on a `helm delete`. Uninstalling the operator does remove the client cert, so we do not need these jobs either
