### ISSUE TITLE
Base ppc and s390x dockerfiles off ubi-minimal:latest tag

### ISSUE THREAD

**Issue by kgcarr** [IBM/ibm-mongodb-operator#52]
We are having vascan issues with the current images.

The easiest solution is to update the tags to `latest`

the other solution is to add `RUN micro-dnf update -y` 

Want to confirm with @chenzhiwei which solution is preferred?

**Comment by chenzhiwei** [comment]
They are already `latest` at time I created the Dockerfile.

**Comment by kgcarr** [comment]
@chenzhiwei they are now out of date...I'll slack you the vascan issue

I'm going to add the update command to make sure when it builds we get the latest package updates.

**Comment by kgcarr** [comment]
```
Installing:
 glibc-langpack-en-2.28-72.el8_1.1.ppc64le      ubi-8-baseos 837.8 kB
Upgrading:
 glibc-2.28-72.el8_1.1.ppc64le                  ubi-8-baseos   5.6 MB
 glibc-common-2.28-72.el8_1.1.ppc64le           ubi-8-baseos 873.4 kB
 glibc-minimal-langpack-2.28-72.el8_1.1.ppc64le ubi-8-baseos  48.8 kB
 libarchive-3.3.2-8.el8_1.ppc64le               ubi-8-baseos 420.2 kB
 openldap-2.4.46-11.el8_1.ppc64le               ubi-8-baseos 386.3 kB
 setup-2.12.2-2.el8_1.1.noarch                  ubi-8-baseos 184.3 kB
 sqlite-libs-3.26.0-4.el8_1.ppc64le             ubi-8-baseos 637.7 kB
 systemd-libs-239-18.el8_1.4.ppc64le            ubi-8-baseos 591.3 kB
```

confirmed adding `RUN microdnf update -y && microdnf clean all` updates the necessary packages
